# Generated by Django 5.0.1 on 2024-02-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0002_certificate_contactprofile_media_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
