# Generated by Django 5.0.1 on 2024-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0003_education_is_active_workexperience_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='Glink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='wlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
