# Generated by Django 5.0.1 on 2024-02-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0004_portfolio_glink_portfolio_wlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Glink',
            new_name='git_link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='wlink',
        ),
    ]
