# Generated by Django 5.0.1 on 2024-02-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0005_rename_glink_portfolio_git_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='technology',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
