# Generated by Django 5.0.1 on 2024-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0007_technology_remove_portfolio_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='technology',
            field=models.ManyToManyField(blank=True, to='portfolio_projects.technology'),
        ),
    ]
