# Generated by Django 5.0.1 on 2024-02-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0008_portfolio_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='technology',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='technology',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
