# Generated by Django 5.0.1 on 2024-02-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0009_remove_portfolio_technology_portfolio_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='technology',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='technology',
            field=models.ManyToManyField(to='portfolio_projects.technology'),
        ),
    ]
